name: playserve_mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you plan to publish
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  pbp_django_auth: ^0.4.0
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/avatar1.png
    - assets/image/avatar2.png
    - assets/image/avatar3.png
    - assets/image/avatar4.png
    - assets/image/avatar5.png
    - assets/image/bgcommunity.png
    - assets/image/search.png
